#!/usr/bin/env python3
# chromeish client

import socket
import sys
import os
import random
import string
import json

cmds = ["ping", "echo", "ls", "open", "cat", "close", "url", "title"]

def setup_socket():
    client = socket.socket(socket.AF_UNIX)
    while True:
        try:
            rand = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(10))
            path = "/tmp/chromeish-{}".format(rand)
            client.bind(path)
        except OSError:
            continue
        break

    try: client.connect("/tmp/shrome")
    except (ConnectionRefusedError, FileNotFoundError):
        print("shrome not running", file=sys.stderr)
        sys.exit()
    return client, path

def formatJSON(arg_list):
    #TODO: advanced argparsing
    query = {
            'text': ' '.join(arg_list)
            }
    json_query = json.dumps(query)
    return json_query


def run():
    arglist = sys.argv[1:]
    cmd_json = formatJSON(arglist)

    client, path = setup_socket()
    client.sendall(cmd_json.encode())

    json_result = client.recvfrom(4096)[0].decode()
    result = json.loads(json_result)
    print(result['text'])

    client.close()
    os.remove(path)

def main():
    if len(sys.argv) < 2:
        print("need arg", file=sys.stderr)
    elif sys.argv[1] not in cmds:
        print("invalid command", file=sys.stderr)
    else:
        run()

if __name__ == "__main__":
    main()
